import Head from "next/head";
import { type FC } from "react";

interface AppProps {
  children: React.ReactNode;
}

const App: FC<AppProps> = ({ children }) => {

  return (
    <>
      <Head>
        <title>Quotus Technical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>{children}</>
    </>
  );
};

export default App;
